config/routes.rb
PjtrackerV11::Application.routes.draw do

  resources :projects do
    resources :tasks, :only => [:create, :edit]
  end

  devise_for :users

  root :to => "projects#index"

  resources :projects do
    get :autocomplete_project_name, :on => :collection
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tasks

     validates :name, :description, :status, :presence => true
     validates :name, :uniqueness => true
     validates :name, :format => { :with => /^[a-zA-Z]+(\w|\s)*$/, :message => "Only letters allowed" }
     validates :status, :length => 4..40
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

    validates :name, :status, :presence => true
    validates :name, :format => { :with => /^[a-zA-Z]+(\w|\s)*$/, :message => "Only letters allowed" }
    validates :status, :length => 5..40
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_and_belongs_to_many :projects
  has_one :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  autocomplete :project, :name
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.paginate(:page => params[:page], :per_page => 5)


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    if @project.project_head != current_user.id
      flash[:alert] = "You are not allowed to edit the project you didnot created"
      redirect_to project_path
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.project_head = current_user.id
    @users = params[:project_user_id]

    if @users.nil?
      flash[:alert] = "Please select atleast one user"
      render :new
    else

      respond_to do |format|
        if @project.save

          @users.each do |u1|
            @u = User.find(u1)
            @project.users<<@u
          end

          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render json: @project, status: :created, location: @project }
        else
          format.html { render action: "new" }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_project
  before_filter :authenticate_user!
  def create
    @tasks = @project.tasks.new(params[:task])
    @tasks.user_id = params[:task_user_id]
    @tasks.save
    redirect_to project_path(@project)
  end

  def edit

  end

  private
  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Project Tracker v1.1" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>

    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="top_nav">
        <% if user_signed_in? %>

        <p>logged in as: <%= current_user.email %> | <%= link_to "log out", destroy_user_session_path, :method => :delete %></p>

        <% else %>
        <p><%= link_to "log in", new_user_session_path %> | <%= link_to "Sign up", new_user_registration_path %></p>
        <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
      <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">

    <%= f.label :name %><br />
    <%= f.autocomplete_field :name, autocomplete_project_name_projects_path %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.datetime_select :deadline %>
  </div>

  <div class="field">
    <%= f.label :user %><br />
    <% User.find(:all).each do |u| %>
    <%= check_box_tag('project_user_id[]', u.id, @project.users.include?(u)) %>
    <%= label_tag(u.id, u.email) %>
    <br />
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Deadline</th>
    <th>Description</th>
    <th>Start date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.status %></td>
    <td><%= project.deadline %></td>
    <td><%= project.description %></td>
    <td><%= project.start_date %></td>
    <td><%= link_to 'Show', project %></td>
    <% if user_signed_in? %>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Name:</b>
  <%= best_in_place @project, :name %>
</p>

<p>
  <b>Created By:</b>
  <% user = User.find(@project.project_head) %>
  <%= user.email%>
</p>

<p>
  <b>Status:</b>
  <%= best_in_place @project, :status %>
</p>

<p>
  <b>Description:</b>
  <%= best_in_place @project, :description, :type => :textarea %>
</p>

<p>
  <b>Start date:</b>
  <%= best_in_place @project, :start_date %>
</p>

<p>
  <b>Deadline:</b>
  <%= best_in_place @project, :deadline %>
</p>

<p>
  <b>Users:</b>
  <% @project.users.each do |user| %>
  <p><%= user.email %></p>
  <% end %>
</p>

<div id="task_container">
  <h2>Tasks</h2>
  <div id="tasks">

    <table width = 100%>
      <tr>
        <td>
          <b>Task Name</b>
        </td>
        <td>
          <b>Assigned to</b>
        </td>
        <td>
          <b>Status</b>
        </td>
        <td>
          <b>Actions</b>
        </td>
      </tr>

      <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= task.name %><br />
        </td>
        <% @user = User.find(task.user_id)%>
        <td>
          <%= @user.email %>
        </td>
        <td>
          <%= task.status %><br />
        </td>
        <td>
          <%= link_to "Edit", edit_project_task_path(@project) %>
        </td>
      </tr>
      <% end %>

      <% if user_signed_in? && (@project.project_head == current_user.id) %>

      <tr id = "task_form">
        <%= form_for([@project, Task.new]) do |f| %>
        <td>
          <%= f.text_field :name, :placeholder => "Task Name" %>
        </td>
        <td>
          <%= select_tag "task_user_id", options_from_collection_for_select(@project.users, "id", "email") %>
        </td>
        <td colspan = 2>
          <%= f.text_field :status, :placeholder => "Status" %>
          <%= f.submit %>
        </td>
        <% end %>


      </tr>

      <% end %>
    </table>
   <%= will_paginate @tasks %>
  </div>
  <br />

</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_task.html.erb
<div id="tasks">
  <table width = 100%>

    <tr>
      <td>
        Task Name
      </td>
      <td>
        Assigned to
      </td>
      <td>
        Status
      </td>
    </tr>

    <tr>
      <td>
        <%= task.name %><br />
      </td>
      <% @user = User.find(task.user_id)%>
      <td>
        <%= @user.email %>
      </td>
      <td>
        <%= task.status %><br />
      </td>
    </tr>
    <tr id = "new task">
      <td>
          <a href = "#">Add Task</a>
      </td>
    </tr>

  </table>
</div>
<br />